# site settings
title: Rappotheek
email: info@info.nl
description: Appotheek van de toekomst
baseurl: ""
permalink: pretty

# collections
collections:
  news:
    output: true

tipue_search:
  include:
    pages: true
    collections: [news]
